/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package melatiputri;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

/**
 *
 * @author Asna Nurfadilah
 * 
 */
public class RabbaniShop extends javax.swing.JFrame {

    /**
     * Creates new form melatiPutris
     */
    public RabbaniShop() {
        initComponents();
        setTitle("Rabbani Putri Shop By Asna Nurfadilah");  
        
        fldNamaBarang.setEditable(false);
        fldBahan.setEditable(false);
        fldUkuran.setEditable(false);
        fldWarna.setEditable(false);
        fldTotalHarga.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNamaBarang = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBahan = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listUkuran = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listWarna = new javax.swing.JList<>();
        lblNamaBarang = new javax.swing.JLabel();
        lblBahan = new javax.swing.JLabel();
        lblUkuran = new javax.swing.JLabel();
        lblWarna = new javax.swing.JLabel();
        fldNamaBarang = new javax.swing.JTextField();
        fldBahan = new javax.swing.JTextField();
        fldUkuran = new javax.swing.JTextField();
        fldWarna = new javax.swing.JTextField();
        fldHarga = new javax.swing.JTextField();
        fldQty = new javax.swing.JTextField();
        fldDiskon = new javax.swing.JTextField();
        fldTotalHarga = new javax.swing.JTextField();
        lblHarga = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        Btotal = new javax.swing.JButton();
        Bulang = new javax.swing.JButton();
        Bkeluar = new javax.swing.JButton();
        lblPersen = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(517, 496));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("RABBANI PUTRI SHOP");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        listNamaBarang.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Segitiga", "2. Segi Empat", "3. Pashmina", "4. Bergo", "5. Syiria" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listNamaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNamaBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listNamaBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 132, 120));

        listBahan.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Sifon", "2. Diamond", "3. Katun", "4. Satin", "5. Sutera" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBahanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listBahan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 101, 120));

        listUkuran.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. S", "2. M", "3. L", "4. XL" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUkuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUkuranMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listUkuran);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 57, 120));

        listWarna.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Merah", "2. Kuning", "3. Hijau", "4. Biru", "5. Hitam", "6. Putih", "7. Coklat", "8. Abu-Abu", "9. Ungu", "10. Pink" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listWarna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listWarnaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listWarna);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, 220));

        lblNamaBarang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNamaBarang.setText("Nama Barang");
        getContentPane().add(lblNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 155, -1));

        lblBahan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBahan.setText("Bahan");
        getContentPane().add(lblBahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        lblUkuran.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUkuran.setText("Ukuran");
        getContentPane().add(lblUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        lblWarna.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWarna.setText("Warna");
        getContentPane().add(lblWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));
        getContentPane().add(fldNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 132, -1));
        getContentPane().add(fldBahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 101, -1));
        getContentPane().add(fldUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 57, -1));
        getContentPane().add(fldWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 100, -1));

        fldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldHargaActionPerformed(evt);
            }
        });
        fldHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldHargaKeyTyped(evt);
            }
        });
        getContentPane().add(fldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 82, -1));

        fldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldQtyKeyTyped(evt);
            }
        });
        getContentPane().add(fldQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 82, -1));

        fldDiskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldDiskonKeyTyped(evt);
            }
        });
        getContentPane().add(fldDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 60, -1));
        getContentPane().add(fldTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 110, -1));

        lblHarga.setText("Harga       ");
        getContentPane().add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        lblQty.setText("Qty           ");
        getContentPane().add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        lblDiscount.setText("Discount   ");
        getContentPane().add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        lblTotalHarga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalHarga.setText("Total Harga");
        getContentPane().add(lblTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        Btotal.setText("TOTAL");
        Btotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtotalActionPerformed(evt);
            }
        });
        getContentPane().add(Btotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        Bulang.setText("ULANG");
        Bulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulangActionPerformed(evt);
            }
        });
        getContentPane().add(Bulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        Bkeluar.setText("KELUAR");
        Bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        lblPersen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPersen.setText("%");
        getContentPane().add(lblPersen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melatiputri/img/rabbani.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melatiputri/img/Background.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        lblBackground.setMaximumSize(new java.awt.Dimension(511, 466));
        lblBackground.setMinimumSize(new java.awt.Dimension(511, 466));
        lblBackground.setPreferredSize(new java.awt.Dimension(511, 466));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkeluarActionPerformed
        // TODO add your handling code here:
        // perintah untuk melakukan keluar dari program
        System.exit(0);
    }//GEN-LAST:event_BkeluarActionPerformed

    private void BtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtotalActionPerformed
        // TODO add your handling code here:
        int hargaAwal, hargaDiskon, hargaAkhir, total;
        
        if (fldNamaBarang.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Barang Harus Dipilih!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldBahan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Jenis Bahan Harus Dipilih !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldUkuran.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ukuran Harus Dipilih !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldWarna.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Jenis Warna Harus Dipilih !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldHarga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Harga Harus Ditentukan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldQty.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Jumlah Barang Harus Ditentukan !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldDiskon.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Diskon Harus Ditentukan !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Pesanan Diprosses !");
            
            hargaAwal = (Integer.parseInt(fldHarga.getText()) * Integer.parseInt(fldDiskon.getText()) / 100);
            hargaDiskon = Integer.parseInt(fldHarga.getText()) - hargaAwal;
            hargaAkhir = hargaDiskon * Integer.parseInt(fldQty.getText());
            fldTotalHarga.setText("Rp. "+hargaAkhir);
        }
        
    }//GEN-LAST:event_BtotalActionPerformed

    private void listNamaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNamaBarangMouseClicked
        // TODO add your handling code here:
        // Perintah dibawah  merupakan perintah untuk mengambil data dari variabel listNamaBarang
        // dan di tampung di variabel fldNamaBarang
        fldNamaBarang.setText(listNamaBarang.getSelectedValue());
    }//GEN-LAST:event_listNamaBarangMouseClicked

    private void listBahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBahanMouseClicked
        // TODO add your handling code here:
        // Perintah dibawah  merupakan perintah untuk mengambil data dari variabel listBahan
        // dan di tampung di variabel fldBahan
        fldBahan.setText(listBahan.getSelectedValue());
    }//GEN-LAST:event_listBahanMouseClicked

    private void listUkuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUkuranMouseClicked
        // TODO add your handling code here:
        // Perintah dibawah  merupakan perintah untuk mengambil data dari variabel listUkuran
        // dan di tampung di variabel listUkuran
        fldUkuran.setText(listUkuran.getSelectedValue());
    }//GEN-LAST:event_listUkuranMouseClicked

    private void listWarnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listWarnaMouseClicked
        // TODO add your handling code here:
        // Perintah dibawah  merupakan perintah untuk mengambil data dari variabel listWarna
        // dan di tampung di variabel fldWarna
        fldWarna.setText(listWarna.getSelectedValue());
    }//GEN-LAST:event_listWarnaMouseClicked

    private void BulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulangActionPerformed
        // TODO add your handling code here:
        // Kode setText("") dengan nilainya kosong merupakan perintah mengapus data yang
        // ada di field fldNamaBarang sampai fldTotalHarga
        fldNamaBarang.setText("");
        fldBahan.setText("");
        fldUkuran.setText("");
        fldWarna.setText("");
        fldHarga.setText("");
        fldQty.setText("");
        fldDiskon.setText("");
        fldTotalHarga.setText("");
    }//GEN-LAST:event_BulangActionPerformed

    void validasiAngka(KeyEvent a){
        if(!Character.isDigit(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null, "Anda Hanya Bisa memasukan Angka Saja !", "Peringatan", JOptionPane.WARNING_MESSAGE);
            //JOptionPane.showMessageDialog(null,"Masukan Angka Saja !");
        } else {
        }
    }
    
    private void fldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldHargaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fldHargaActionPerformed

    private void fldHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldHargaKeyTyped
        // TODO add your handling code here:
        validasiAngka(evt);
    }//GEN-LAST:event_fldHargaKeyTyped

    private void fldQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldQtyKeyTyped
        // TODO add your handling code here:
        validasiAngka(evt);
    }//GEN-LAST:event_fldQtyKeyTyped

    private void fldDiskonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldDiskonKeyTyped
        // TODO add your handling code here:
        validasiAngka(evt);
    }//GEN-LAST:event_fldDiskonKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RabbaniShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RabbaniShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RabbaniShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RabbaniShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RabbaniShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bkeluar;
    private javax.swing.JButton Btotal;
    private javax.swing.JButton Bulang;
    private javax.swing.JTextField fldBahan;
    private javax.swing.JTextField fldDiskon;
    private javax.swing.JTextField fldHarga;
    private javax.swing.JTextField fldNamaBarang;
    private javax.swing.JTextField fldQty;
    private javax.swing.JTextField fldTotalHarga;
    private javax.swing.JTextField fldUkuran;
    private javax.swing.JTextField fldWarna;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBahan;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblPersen;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblUkuran;
    private javax.swing.JLabel lblWarna;
    private javax.swing.JList<String> listBahan;
    private javax.swing.JList<String> listNamaBarang;
    private javax.swing.JList<String> listUkuran;
    private javax.swing.JList<String> listWarna;
    // End of variables declaration//GEN-END:variables
    DefaultListModel mdl = new DefaultListModel();
}
