/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package melatiputri;

// untu mengimport library java
import java.awt.event.KeyEvent;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import com.placeholder.PlaceHolder;

/**
 *
 * @author Asna Nurfadilah
 * 
 */
public class RabbaniShop extends javax.swing.JFrame {

    /**
     * Creates new form melatiPutris
     */
    public RabbaniShop() {
        initComponents();
        // SetTitle untuk memberikan Title ke program
        setTitle("Rabbani Putri Shop By Asna Nurfadilah");  
        
        // Awal
        // setEditable(false) agar field tidak bisa dinput user
        fldNamaBarang.setEditable(false);
        fldBahan.setEditable(false);
        fldUkuran.setEditable(false);
        fldWarna.setEditable(false);
        fldTotalHarga.setEditable(false);
        areaRincian.setEditable(false);
        // Akhir
        
        // untuk memberikan Placeholder ke variabel fldHarag, fldQty dan fldDiskon
        PlaceHolder holder1 = new PlaceHolder(fldHarga,"Harga...");
        PlaceHolder holder2 = new PlaceHolder(fldQty, "Jumlah...");
        PlaceHolder holder3 = new PlaceHolder(fldDiskon, "Diskon...");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listNamaBarang = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listBahan = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listUkuran = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listWarna = new javax.swing.JList<>();
        lblNamaBarang = new javax.swing.JLabel();
        lblBahan = new javax.swing.JLabel();
        lblUkuran = new javax.swing.JLabel();
        lblWarna = new javax.swing.JLabel();
        fldNamaBarang = new javax.swing.JTextField();
        fldBahan = new javax.swing.JTextField();
        fldUkuran = new javax.swing.JTextField();
        fldWarna = new javax.swing.JTextField();
        fldHarga = new javax.swing.JTextField();
        fldQty = new javax.swing.JTextField();
        fldDiskon = new javax.swing.JTextField();
        fldTotalHarga = new javax.swing.JTextField();
        lblHarga = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        Btotal = new javax.swing.JButton();
        Bulang = new javax.swing.JButton();
        Bkeluar = new javax.swing.JButton();
        lblPersen = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaRincian = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(517, 496));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setText("RABBANI PUTRI SHOP");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        listNamaBarang.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Segitiga", "2. Segi Empat", "3. Pashmina", "4. Bergo", "5. Syiria", "6. Rajut", "7. Jumbo", "8. Hoodie", "9. Cape", "10. Polyster" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listNamaBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listNamaBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listNamaBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 132, 120));

        listBahan.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Sifon", "2. Diamond", "3. Katun", "4. Satin", "5. Sutera", "6. Spandex", "7. Voile", "8. Ceruti", "9. Wolfis", "10. Rayon" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listBahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listBahanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listBahan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 100, 120));

        listUkuran.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. S", "2. M", "3. L", "4. XL", "5. XXL" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUkuran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listUkuranMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listUkuran);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 90, 120));

        listWarna.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Merah", "2. Kuning", "3. Hijau", "4. Biru", "5. Hitam", "6. Putih", "7. Coklat", "8. Abu-Abu", "9. Ungu", "10. Pink" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listWarna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listWarnaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listWarna);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, 120));

        lblNamaBarang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNamaBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNamaBarang.setText("Nama Barang");
        getContentPane().add(lblNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, -1));

        lblBahan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBahan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBahan.setText("Bahan");
        getContentPane().add(lblBahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 110, 100, 20));

        lblUkuran.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUkuran.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUkuran.setText("Ukuran");
        getContentPane().add(lblUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 110, 80, -1));

        lblWarna.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblWarna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarna.setText("Warna");
        getContentPane().add(lblWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 100, -1));

        fldNamaBarang.setText("Pilih Barang");
        getContentPane().add(fldNamaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 132, -1));

        fldBahan.setText("Pilih Bahan");
        getContentPane().add(fldBahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 101, -1));

        fldUkuran.setText("Pilih Bahan");
        getContentPane().add(fldUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 90, -1));

        fldWarna.setText("Pilih Bahan");
        getContentPane().add(fldWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 100, -1));

        fldHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldHargaKeyTyped(evt);
            }
        });
        getContentPane().add(fldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 82, -1));

        fldQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldQtyKeyTyped(evt);
            }
        });
        getContentPane().add(fldQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 82, -1));

        fldDiskon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fldDiskonKeyTyped(evt);
            }
        });
        getContentPane().add(fldDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 60, -1));
        getContentPane().add(fldTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 120, -1));

        lblHarga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHarga.setText("Harga       ");
        getContentPane().add(lblHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

        lblQty.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQty.setText("Qty           ");
        getContentPane().add(lblQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

        lblDiscount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDiscount.setText("Discount   ");
        getContentPane().add(lblDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, 20));

        lblTotalHarga.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTotalHarga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotalHarga.setText("Total Harga");
        getContentPane().add(lblTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 120, -1));

        Btotal.setText("TOTAL");
        Btotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtotalActionPerformed(evt);
            }
        });
        getContentPane().add(Btotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        Bulang.setText("ULANG");
        Bulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulangActionPerformed(evt);
            }
        });
        getContentPane().add(Bulang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        Bkeluar.setText("KELUAR");
        Bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        lblPersen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPersen.setText("%");
        getContentPane().add(lblPersen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melatiputri/img/rabbani.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        areaRincian.setColumns(20);
        areaRincian.setRows(5);
        jScrollPane5.setViewportView(areaRincian);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 240, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Rincian");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 240, -1));

        lblBackground.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melatiputri/img/Background.jpg"))); // NOI18N
        lblBackground.setText("jLabel1");
        lblBackground.setMaximumSize(new java.awt.Dimension(511, 466));
        lblBackground.setMinimumSize(new java.awt.Dimension(511, 466));
        lblBackground.setPreferredSize(new java.awt.Dimension(511, 466));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BkeluarActionPerformed
        // perintah untuk melakukan keluar dari program ketika di klik tombol keluar
        System.exit(0);
    }//GEN-LAST:event_BkeluarActionPerformed

    private void BtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtotalActionPerformed
        // variabel hargaAwal, sampe hargaAkhir untuk menampung nilai menggunakan tipe data integer
        // variabel Asna1 sampe asna7 digunakan untuk menampung data, menggunakan tipe data string
        int hargaAwal, hargaDiskon, hargaAkhir;
        String asna1, asna2, asna3, asna4, asna5, asna6, asna7;
        
        /* Awal 
         * Variabel Asna1 sampe asna7 akan menampung data dari variabel fldnamaBarang sampe fldDiskon */
        asna1 = fldNamaBarang.getText();
        asna2 = fldBahan.getText();
        asna3 = fldUkuran.getText();
        asna4 = fldWarna.getText();
        asna5 = fldHarga.getText();
        asna6 = fldQty.getText();
        asna7 = fldDiskon.getText();
        /* Akhir */
        
        // if else untuk JOptionPane untuk memberikan pesan error ketika user tidak mengisi field
        if (fldNamaBarang.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol total
            JOptionPane.showMessageDialog(null, "Barang Harus Dipilih!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldBahan.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol total
            JOptionPane.showMessageDialog(null, "Jenis Bahan Harus Dipilih !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldUkuran.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol total
            JOptionPane.showMessageDialog(null, "Ukuran Harus Dipilih !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldWarna.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol total
            JOptionPane.showMessageDialog(null, "Jenis Warna Harus Dipilih !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldHarga.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol total
            JOptionPane.showMessageDialog(null, "Harga Harus Ditentukan!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldQty.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol total
            JOptionPane.showMessageDialog(null, "Jumlah Barang Harus Ditentukan !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else if (fldDiskon.getText().equals("")) {
            // Pesan Dialog Ketika user tidak mengisi field akan ada informasi error ketika sudahklik tombol total
            JOptionPane.showMessageDialog(null, "Diskon Harus Ditentukan !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        } else {
            // Pesan Dialog Ketika user klik tombol total
            JOptionPane.showMessageDialog(null, "Pesanan Diprosses !");
            
            // hargaAwal untuk mengkalikan nilai dari variabel fldHarga dan fldDiskon lalu akan dibagi 100
            // hargaDiskon untuk mengurangi agar mendapattkan harga diskon
            // hargaAkhir untuk mengkalikan harga yang telah mendapatkan dengan diskon dengan data dari variabel fldQty
            // fldTotalHarga settext untuk menampilkan data dari vvariabel hargaAkhir
            hargaAwal = (Integer.parseInt(fldHarga.getText()) * Integer.parseInt(fldDiskon.getText()) / 100);
            hargaDiskon = Integer.parseInt(fldHarga.getText()) - hargaAwal;
            hargaAkhir = hargaDiskon * Integer.parseInt(fldQty.getText());
            fldTotalHarga.setText("Rp. "+hargaAkhir);
            
            // Awal
            // Menampilkan Hasil Input dari User secara rinci Ke text area
            areaRincian.setText(areaRincian.getText()
                                +"Nama Barang \t: "+ asna1 +
                                "\nNama Bahan \t: "+ asna2+
                                "\nUkuran  \t: "+ asna3+
                                "\nWarna \t: "+ asna4+
                                "\nJumlah \t: "+ asna6+
                                "\nDiskon \t: "+ asna7+"%"+
                                "\nHarga Satuan \t: Rp. "+ asna5
            );
            // Akhir
        }
        
    }//GEN-LAST:event_BtotalActionPerformed

    private void listNamaBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listNamaBarangMouseClicked
        // Perintah dibawah  merupakan perintah untuk mengambil data dari variabel listNamaBarang
        // dan di tampung di variabel fldNamaBarang
        fldNamaBarang.setText(listNamaBarang.getSelectedValue());
    }//GEN-LAST:event_listNamaBarangMouseClicked

    private void listBahanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listBahanMouseClicked
        // Perintah dibawah  merupakan perintah untuk mengambil data dari variabel listBahan
        // dan di tampung di variabel fldBahan
        fldBahan.setText(listBahan.getSelectedValue());
    }//GEN-LAST:event_listBahanMouseClicked

    private void listUkuranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listUkuranMouseClicked
        // Perintah dibawah  merupakan perintah untuk mengambil data dari variabel listUkuran
        // dan di tampung di variabel listUkuran
        fldUkuran.setText(listUkuran.getSelectedValue());
    }//GEN-LAST:event_listUkuranMouseClicked

    private void listWarnaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listWarnaMouseClicked
        // Perintah dibawah  merupakan perintah untuk mengambil data dari variabel listWarna
        // dan di tampung di variabel fldWarna
        fldWarna.setText(listWarna.getSelectedValue());
    }//GEN-LAST:event_listWarnaMouseClicked

    private void BulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulangActionPerformed
        // TODO add your handling code here:
        // Kode setText("") dengan nilainya kosong merupakan perintah mengapus data yang
        // ada di field fldNamaBarang sampai fldTotalHarga
        fldNamaBarang.setText("");
        fldBahan.setText("");
        fldUkuran.setText("");
        fldWarna.setText("");
        fldHarga.setText("");
        fldQty.setText("");
        fldDiskon.setText("");
        fldTotalHarga.setText("");
        areaRincian.setText("");
    }//GEN-LAST:event_BulangActionPerformed

    
    // function VaidasiAngka untuk memberikan pesan error pada field ketika user salah nginput
    void validasiAngka(KeyEvent a){
        if(!Character.isDigit(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null, "Anda Hanya Bisa Memasukan Angka Saja !", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void fldHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldHargaKeyTyped
        // pesan input kesalahan dari function validasiAngka
        validasiAngka(evt);
    }//GEN-LAST:event_fldHargaKeyTyped

    private void fldQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldQtyKeyTyped
        // pesan input kesalahan dari function validasiAngka
        validasiAngka(evt);
    }//GEN-LAST:event_fldQtyKeyTyped

    private void fldDiskonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fldDiskonKeyTyped
        // pesan input kesalahan dari function validasiAngka
        validasiAngka(evt);
    }//GEN-LAST:event_fldDiskonKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RabbaniShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RabbaniShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RabbaniShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RabbaniShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RabbaniShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bkeluar;
    private javax.swing.JButton Btotal;
    private javax.swing.JButton Bulang;
    private javax.swing.JTextArea areaRincian;
    private javax.swing.JTextField fldBahan;
    private javax.swing.JTextField fldDiskon;
    private javax.swing.JTextField fldHarga;
    private javax.swing.JTextField fldNamaBarang;
    private javax.swing.JTextField fldQty;
    private javax.swing.JTextField fldTotalHarga;
    private javax.swing.JTextField fldUkuran;
    private javax.swing.JTextField fldWarna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBahan;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNamaBarang;
    private javax.swing.JLabel lblPersen;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalHarga;
    private javax.swing.JLabel lblUkuran;
    private javax.swing.JLabel lblWarna;
    private javax.swing.JList<String> listBahan;
    private javax.swing.JList<String> listNamaBarang;
    private javax.swing.JList<String> listUkuran;
    private javax.swing.JList<String> listWarna;
    // End of variables declaration//GEN-END:variables
    // default list Model mdl
    DefaultListModel mdl = new DefaultListModel();
}
